version: 2

sources:
  - name: raw_data
    description: "Raw taxi trip data from NYC TLC"
    database: taxi_rides_ny #Bigquery: google Bigquery project ID
    schema: prod #Bigquery: dataset name
   
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
        